[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m http.server 8080"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "pronunciation-trainer"
source = "."