[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Variables de entorno que Railway debe configurar
SECRET_KEY = ""
DEBUG = "False"
DATABASE_URL = ""
RAILWAY_PUBLIC_DOMAIN = ""
FRONTEND_URL = ""